### ISSUE TITLE
Spark 3 / Cassandra 4 / Java 11 upgrade

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#38]

**Comment by behas** [comment]
Currently not possible because of spark-cassandra connector problem: fields of type blob cannot be in nested type

**Comment by defconst** [comment]
Error message

```
[2021-02-10 15:26:25] Writing table address
21/02/10 15:26:41 ERROR executor.Executor: Exception in task 2.0 in stage 227.0 (TID 11632)
com.datastax.oss.driver.api.core.type.codec.CodecNotFoundException: Codec not found for requested operation: [BLOB <-> java.nio.HeapByteBuffer]
```

Versions
```
      "org.apache.spark" %% "spark-sql" % "3.0.1" % Provided,                   
      "com.datastax.spark" %% "spark-cassandra-connector" % "3.0.0" % Provided
```

**Comment by QuentinFAIDIDE** [comment]
Here is an example of a driver for blob to int conversion, maybe it's possible to write one for blob to HeapByteBuffer and include it in the spark job jars to fix this ?
https://gist.github.com/adutra/9f09f1c8e377ee774f6388d5fb073045
I will keep you updated if I find anything that makes it work.

**Comment by QuentinFAIDIDE** [comment]
It may be due to a faulty test in the CachingCodedRegistry class from datastax java-driver library.
I 've been able to get the `Coded: blob -> HeapByteBuffer` error to disappear by building a modified java-driver jar where I changed some class type tests around the thrown CodecNotFoundException.
Then by passing it to the spark transformation job it ended up working. I will provide more details soon as I try to run the transformation on some more blocks and A/B the changes I made to java-driver to know which one made it work.

**Comment by QuentinFAIDIDE** [comment]
[Here are](https://github.com/QuentinFAIDIDE/graphsense-transformation/tree/spark3-building/jars) the jars I used if you guys want to try. 

The sbt versions are the following:
```sbt
ThisBuild / scalaVersion := "2.12.10"
ThisBuild / organization := "at.ac.ait"
ThisBuild / version      := "0.5.0"


lazy val root = (project in file(".")).
  settings(
    name := "graphsense-transformation",
    fork := true,
    testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-oD"),
    scalacOptions ++= List(
      "-deprecation",
      "-feature",
      "-unchecked",
      "-Xlint:_",
      "-Ywarn-adapted-args",
      "-Ywarn-dead-code",
      "-Ywarn-inaccessible",
      "-Ywarn-infer-any",
      "-Ywarn-nullary-override",
      "-Ywarn-nullary-unit",
      "-Ywarn-numeric-widen",
      "-Ywarn-unused",
      "-Ywarn-unused-import",
      "-Ywarn-value-discard"),
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.2.7" % Test,
      "com.github.mrpowers" % "spark-fast-tests_2.12" % "0.23.0" % Test,
      "org.rogach" %% "scallop" % "4.0.2" % Provided,
      "org.apache.spark" %% "spark-sql" % "3.0.0" % Provided,
      "com.datastax.spark" %% "spark-cassandra-connector" % "3.0.0" % Provided)
  )
```

Make sure to be carefull with the spark-submit package option, I had to include all the jars manually because I think the --packeges arg was overwriting my jars with one from maven.

**Comment by adutra** [comment]
Hi, Cassandra driver dev here.

The error you are seeing is:

```
CodecNotFoundException: Codec not found for requested operation: [BLOB <-> java.nio.HeapByteBuffer]
```

`HeapByteBuffer` is not the right type for a BLOB column. It should be `ByteByffer`.

Please check all the calls to any of the `codecFor` methods in the `CodecRegistry` interface for wrong parameters.

**Comment by defconst** [comment]
Removed tx hash BLOB columns in 2c99c24
